package sec6;

import java.util.Random;
import java.util.stream.Stream;

public class GenerateStreamExample {

    // stream.of() create a stream of similar type of data
    // we have created stream using Arrays.asList(1,2,3) for stream = stream.of()

    // iterate generate a sequence of infinite sequential Ordered stream
    // seed is the inital element of stream

    // generate is an infinite sequential unordered stream where each element is generated by the provided supplier


    public static void main(String[] args) {

        // of
        Stream<Integer> stream = Stream.of(1,2,3,4,5,6);
        stream.forEach(System.out::println);

        // iterate
        Stream<Integer> stream1 = Stream.iterate(0,i->i+1).limit(10);
        stream1.forEach(System.out::println);

        // gnerate
        Stream<Integer> stream3 = Stream.generate(new Random()::nextInt).limit(10);
        stream1.forEach(System.out::println);


    }


}
